config/routes.rb
Rails.application.routes.draw do

  resources :ningens do
    resources :tasks, only: [:create, :destroy]
  end
  root  'ningens#index'

end

app/models/ningen.rb
class Ningen < ActiveRecord::Base
	has_many :tasks
	validates :name, presence: {message: "せめて名前ぐらい入れろや"},
			         length: {minimum: 2, message: "2文字以上の名前を入れてくれやい"}
	validates :description, presence: {message: "せめて説明ぐらい入れろや"},
			         length: {minimum: 6, message: "6文字以上の名前を入れてくれやい"}
	validates :img_url, presence: {message: "画像のURLをいれてね"}
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :ningen
  validates :age, presence: {message: "年齢をいれてください"}
  validates :event, presence: {message: "出来事をいれてください"},
  					length: {minimum: 6, message: "6文字以上でお願いしますね"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
end

app/controllers/ningens_controller.rb
class NingensController < ApplicationController

	def index
		@ningens = Ningen.all
	end

	def show
		@ningen = Ningen.find(params[:id])
	end

	def new
		@ningen = Ningen.new
	end

	def create
		@ningen = Ningen.new(ningen_params)
		if @ningen.save
			redirect_to root_path
		else
			render "new"
		end
	end

	def edit
		@ningen = Ningen.find(params[:id])
	end

	def update
		@ningen = Ningen.find(params[:id])
		if @ningen.update(ningen_params)
			redirect_to @ningen
		else
			render "edit"
		end
	end

	def destroy
		@ningen = Ningen.find(params[:id])
		@ningen.destroy
		redirect_to root_path
	end

	private

	def ningen_params
		params[:ningen].permit(:name, :description, :category, :img_url, :ningen_id)
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	#before_action: set_task , only %w(create)

	def create
		@ningen = Ningen.find(params[:ningen_id])
		@task = @ningen.tasks.create(task_params)
		redirect_to @ningen
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to ningen_path(params[:ningen_id])
	end

	private

	#def set_task
		#@ningen = Ningen.find(params[:ningen_id])
	#end

	def task_params
		params[:task].permit(:age, :event)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/ningens_helper.rb
module NingensHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Anotoki
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      %span.navbar-brand
        = link_to "ANOTOKI", root_path
    .container
      = yield
      .bottan.btn-group
        %p.btn= link_to "home", root_path , :class => "btn btn-default"
        %p.btn= link_to "new", new_ningen_path , :class => "btn btn-default"

app/views/ningens/edit.html.haml
%h1 edit
= form_for @ningen do |f|
  %p
    = f.label :name
    %br/
    = f.text_field :name
    - if @ningen.errors.any?
      = @ningen.errors.messages[:name][0]
  %p
    = f.label :description
    %br/
    = f.text_field :description
  %p
    = f.label :category
    %br/
    / <haml_loud> f.text_field :category </haml_loud>
    = f.select :category, ["経営者", "実業家", "発明家", "芸術家", "政治家"]
  %p
    = f.label :img_url
    %br/
    = f.text_field :img_url
  %p
    = f.submit "更新"

app/views/ningens/index.html.haml
%ul
  - @ningens.each do |ningens|
    %li
      .left
        .list_face
          = image_tag (ningens.img_url)
      %h2= link_to ningens.name, ningens
      %h4= ningens.description
      %p= ningens.category

app/views/ningens/new.html.haml
%h1 新しい人物を追加する
= form_for @ningen do |f|
  %p
    = f.label :name
    %br/
    = f.text_field :name
    - if @ningen.errors.any?
      = @ningen.errors.messages[:name][0]
  %p
    = f.label :description
    %br/
    = f.text_field :description
    - if @ningen.errors.any?
      = @ningen.errors.messages[:description][0]
  %p
    = f.label :category
    %br/
    / <haml_loud> f.text_field :category </haml_loud>
    = f.select :category, ["経営者", "実業家", "発明家", "芸術家", "政治家"]
  %p
    = f.label :img_url
    %br/
    = f.text_field :img_url
    - if @ningen.errors.any?
      = @ningen.errors.messages[:img_url][0]
  %p
    = f.submit "Create"

app/views/ningens/show.html.haml
%div.rails.s.bs-docs-header
  .header_area
    .image
      = image_tag (@ningen.img_url)
    .main_right
      %h2.name
        = @ningen.name
        %span.category= @ningen.category
      %p.description
        = @ningen.description
.container
  - @ningen.tasks.each do |task|
    .age_content
      %p.age
        = task.age
        %span 歳
      %p.event= task.event
      %p= link_to "delete", ningen_task_path(task.ningen_id, task.id), method: :delete, data: { |
      confirm: "are you sure"} , :class => "btn btn-default"  |
.form-group
  %p
    = form_for [@ningen, @ningen.tasks.build] do |f|
      %p
        = f.label :年齢
        = f.text_field :age
      %p
        = f.label :イベント
        = f.text_field :event
      = f.submit(["イベントを追加する"])
.bottan
  %p= link_to "edit", edit_ningen_path , :class => "btn btn-default"
  %p= link_to "delete", ningen_path, method: :delete, data: { |
      confirm: "are you sure"} , :class => "btn btn-default"  |